production:
  adapter: postgresql
  database: discourse_prod
  username: discourse_prod_user
  password: md51901ffbaadaa01a9c750d614dc0e03d4
  host: 15.185.183.148
  pool: 5 # size of DB connection pool *per process*
  timeout: 5000
  # db_id: 0 # database ID if hosting multiple sites
  host_names:
    ### If you change this setting you will need to
    ### - restart sidekiq if you change this setting
    ### - rebake all to posts using: `RAILS_ENV=production bundle exec rake posts:rebake`
    - discourse.mozilla-community.org # Update this to be the domain of your production site

dev:
  adapter: postgresql
  database: discourse_dev
  username: discourse_dev_user
  password: md5a05ed52d1344dcf1575b556ae9416f4a
  min_messages: warning
  host: localhost
  pool: 5
  timeout: 5000
  host_names:
    - dev.discourse.mozilla-community.org

stage:
  adapter: postgresql
  database: discourse_stage
  username: discourse_stage_user
  password: md53261a03c46af9ced5034c696ec76f0d5
  min_messages: warning
  host: localhost
  pool: 5
  timeout: 5000
  host_names:
    - stage.discourse.mozilla-community.org